name: python-deployment
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
    python-ci:
      runs-on: ubuntu-latest

      steps:

      - uses: actions/checkout@v4
