name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions

env:
  APP_ENV: PythonApp
  GITHUB_ACTIONS: "true"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CONFIG_TYPE: Debug
      PYTHON_VERSION: 3.8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
    - run: echo "${{ env.APP_ENV }} - ${{ env.CONFIG_TYPE }} - ${{ env.PYTHON_VERSION }}"
    - run: echo "Job was triggered by event ${{ github.event_name }}"
    - run: echo "This job is executed on a runner with os ${{ runner.os }}"
    - run: echo "Name of the branch ${{ github.ref }} and your repository ${{ github.repository }}"
    - run: echo "This job's status is ${{ job.status }}"
